version: '3'
services:
  chatbot:
    build: .
    container_name: chatbot
    ports:
      - "10000:10000"
    environment:
      - T_ACCESS_TOKEN=${T_ACCESS_TOKEN}
      - C_ACCESS_TOKEN=${C_ACCESS_TOKEN}
      - T_LINK=${T_LINK}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 30s
      timeout: 5s
      retries: 3