# Infrastructure as Code (IaC)
services:
  - type: worker
    name: ChatGPTBot
    runtime: docker
    dockerfile: Dockerfile
    envVars:
      - key: T_ACCESS_TOKEN
        sync: false  
      - key: C_ACCESS_TOKEN
        sync: false
      - key: T_LINK
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
    autoScaling:
      enabled: true
      minInstances: 1
      maxInstances: 3
      cpuThreshold: 60
    healthCheckPath: /health
    restartPolicy: always
    maxRestarts: 10
    port: 10000