name: Deploy to Cloud Run
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build and deploy
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: telegram-bot
          region: us-central1
          source: .
          env_vars: |
            T_ACCESS_TOKEN=${{ secrets.T_ACCESS_TOKEN }}
            C_ACCESS_TOKEN=${{ secrets.C_ACCESS_TOKEN }}
            T_LINK=${{ secrets.T_LINK }}
            FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}
          secrets: |
            FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}:latest