name: Deploy to Cloud Run
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Build and deploy
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: "telegram-chatbot" 
          region: "asia-east2"        
          source: "."
          env_vars: |
            T_ACCESS_TOKEN=${{ secrets.T_ACCESS_TOKEN }}
            C_ACCESS_TOKEN=${{ secrets.C_ACCESS_TOKEN }}
            T_LINK=${{ secrets.T_LINK }}
            FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}
          flags: |
            --cpu=1
            --memory=512Mi
            --min-instances=1
            --timeout=300s