name: Force Render Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Cancel active deployments
        id: cancel-build
        run: |
          # Get active deployments
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys?status=created|building|pending")
          
          # Cancel all active builds
          echo "$RESPONSE" | jq -r '.[].id' | while read DEPLOY_ID; do
            echo "Cancelling deployment $DEPLOY_ID"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID"
          done

      - name: Trigger fresh deployment
        uses: sws2apps/render-deployment@v1.2.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
          waitForDeployment: true
          deploymentTimeout: 600  # 10 minute timeout

      - name: Verify deployment
        run: |
          echo "Waiting 30s for deployment to stabilize..."
          sleep 30
          curl -sSf https://${{ secrets.RENDER_SERVICE_NAME }}.onrender.com/health