name: Render Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://cli.render.com/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH  # Add to PATH

      # Deploy to Render
      - name: Deploy
        run: render deploy --service telegram-bot --wait
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}