name: Trigger Render Build
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"ref":"${{ github.ref }}"}' \
            "${{ secrets.RENDER_WEBHOOK_URL }}"